"""Build the demo as a static site.

The interactive part of the GUI is already client-side: once the browser holds a
run payload, the trade-off slider, map, objective bars, load table and CSV export
all work without touching the server. Only the solve itself needs Python.

So the demo can ship to plain static hosting by pre-solving a grid of slider
positions ahead of time and writing one JSON payload per grid point. The page
then fetches a prebaked file instead of posting to ``/api/run``.

Grid points are addressed by the **index** of each slider value rather than the
value itself, so the builder and the browser can never disagree about how to
format a float.

    pva build-demo --output dist/

The result is a directory of static files, deployable exactly like an Astro
``dist/``.
"""

from __future__ import annotations

import json
import logging
import shutil
from concurrent.futures import ProcessPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from presidio_vol_assign.web.runner import RunRequest, _solve
from presidio_vol_assign.web.scenarios import SCENARIOS, Scenario

log = logging.getLogger("presidio_vol_assign.web.static")

STATIC_SRC = Path(__file__).parent / "static"


# ---------------------------------------------------------------------------
# The grid
# ---------------------------------------------------------------------------

# Which slider positions are pre-solved, per knob. Chosen to span the
# interesting range rather than to be exhaustive: a handful of well-separated
# options reads better to a non-specialist than a near-continuous slider, and
# every extra axis multiplies build time and hosted bytes.
_COMPACT_GRID: dict[str, list[float]] = {
    "n_people": [30, 80, 150, 300],
    "n_centers": [3, 5, 8],
    "capacity_slack": [1.0, 1.2, 1.5],
    "vulnerability": [3.0, 5.0, 7.0],
    "max_distance": [30],
    "n_volunteers": [20, 60, 120, 200],
    "n_vacancies": [6, 12, 24],
    "n_eds": [2, 3, 5],
    "emergency_level": [4.0, 6.0, 8.0],
}

_FULL_GRID: dict[str, list[float]] = {
    **_COMPACT_GRID,
    "n_centers": [3, 5, 8, 12],
    "capacity_slack": [1.0, 1.2, 1.5, 2.0],
    "max_distance": [20, 30, 50],
}

SEEDS = [42, 7]
"""Pre-solved seeds. Each is a different synthetic affected area."""

STATIC_SOLVER = "both"
"""Pre-solve both solvers so the run-quality table can compare them."""

STATIC_GENERATIONS = 120

# Apache config for the hosted build. The run payloads are highly repetitive
# JSON and compress by roughly 5x, which matters because the largest is ~150 kB
# uncompressed. They are also immutable between builds, so they can be cached
# hard; config.json and the page itself must not be, or a redeploy would leave
# visitors on a stale grid.
_HTACCESS = """\
# Generated by `pva build-demo` — do not edit by hand.

<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE application/json application/javascript text/css text/html
</IfModule>

<IfModule mod_headers.c>
    # Pre-solved runs change only when the demo is rebuilt.
    <FilesMatch "\\.json$">
        Header set Cache-Control "public, max-age=86400"
    </FilesMatch>
    # The grid definition and the page must always reflect the current build.
    <Files "config.json">
        Header set Cache-Control "no-cache"
    </Files>
    <FilesMatch "\\.(html|js|css)$">
        Header set Cache-Control "no-cache"
    </FilesMatch>
    Header set X-Content-Type-Options "nosniff"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"
</IfModule>

<IfModule mod_mime.c>
    AddType application/json .json
</IfModule>

Options -Indexes
"""


@dataclass(frozen=True)
class GridPoint:
    """One pre-solved combination."""

    scenario_id: str
    knob_indices: tuple[int, ...]
    seed_index: int
    knobs: dict[str, float]
    seed: int

    @property
    def key(self) -> str:
        """Filesystem- and URL-safe identifier, addressed purely by index."""
        idx = "-".join(str(i) for i in self.knob_indices)
        return f"{idx}__s{self.seed_index}"

    @property
    def rel_path(self) -> str:
        return f"runs/{self.scenario_id}/{self.key}.json"


def _grid_values(scenario: Scenario, grid: dict[str, list[float]]) -> list[list[float]]:
    """Ordered value lists for each of *scenario*'s knobs."""
    values = []
    for knob in scenario.knobs:
        options = grid.get(knob.key)
        if not options:
            options = [knob.default]
        # Keep only values the knob itself accepts, so the grid can never
        # produce a request the server would clamp to something different.
        values.append([knob.clamp(v) for v in options])
    return values


def _enumerate(scenario: Scenario, grid: dict[str, list[float]]) -> list[GridPoint]:
    """Every grid point for one scenario."""
    value_lists = _grid_values(scenario, grid)
    points: list[GridPoint] = []

    def walk(depth: int, chosen: list[int]) -> None:
        if depth == len(value_lists):
            knobs = {knob.key: value_lists[i][chosen[i]] for i, knob in enumerate(scenario.knobs)}
            for si, seed in enumerate(SEEDS):
                points.append(
                    GridPoint(
                        scenario_id=scenario.id,
                        knob_indices=tuple(chosen),
                        seed_index=si,
                        knobs=dict(knobs),
                        seed=seed,
                    )
                )
            return
        for i in range(len(value_lists[depth])):
            walk(depth + 1, [*chosen, i])

    walk(0, [])
    return points


def plan(grid_name: str = "compact") -> tuple[list[GridPoint], dict[str, list[list[float]]]]:
    """Return every grid point to solve, plus the per-scenario value lists."""
    grid = _FULL_GRID if grid_name == "full" else _COMPACT_GRID
    points: list[GridPoint] = []
    values: dict[str, list[list[float]]] = {}
    for scenario in SCENARIOS:
        values[scenario.id] = _grid_values(scenario, grid)
        points.extend(_enumerate(scenario, grid))
    return points, values


# ---------------------------------------------------------------------------
# Solving
# ---------------------------------------------------------------------------


def _solve_point(payload: dict[str, Any]) -> dict[str, Any]:
    """Solve one grid point in a worker process.

    The solver and generation count travel in *payload* rather than being read
    from module globals: under the ``spawn`` start method a worker re-imports
    this module fresh, so it would not see values overridden in the parent.
    """
    request = RunRequest(
        scenario_id=payload["scenario_id"],
        knobs=payload["knobs"],
        solver=payload["solver"],
        seed=payload["seed"],
        generations=payload["generations"],
    )
    return _solve(request.as_dict())


def _config(values: dict[str, list[list[float]]], points: list[GridPoint]) -> dict[str, Any]:
    """The static equivalent of ``GET /api/scenarios``."""
    from presidio_vol_assign.web.app import _package_version

    counts: dict[str, int] = {}
    for point in points:
        counts[point.scenario_id] = counts.get(point.scenario_id, 0) + 1

    scenarios = []
    for scenario in SCENARIOS:
        as_dict = scenario.as_dict()
        # Replace continuous slider bounds with the pre-solved positions.
        for knob_dict, options in zip(as_dict["knobs"], values[scenario.id]):
            knob_dict["values"] = options
        as_dict["runCount"] = counts.get(scenario.id, 0)
        scenarios.append(as_dict)

    return {
        "version": _package_version(),
        "mode": "static",
        "scenarios": scenarios,
        "seeds": SEEDS,
        "solver": STATIC_SOLVER,
        "generations": STATIC_GENERATIONS,
    }


def build(
    output: Path,
    *,
    grid_name: str = "compact",
    workers: int | None = None,
    progress: Any = None,
) -> dict[str, Any]:
    """Build the static demo into *output*. Returns a short summary.

    Args:
        output: Target directory. Created if absent; ``runs/`` is replaced.
        grid_name: ``"compact"`` (default) or ``"full"``.
        workers: Solver processes to use. Defaults to the executor's default.
        progress: Optional callable ``(done, total)`` for progress reporting.
    """
    points, values = plan(grid_name)
    output.mkdir(parents=True, exist_ok=True)

    for name in ("app.js", "style.css"):
        shutil.copy2(STATIC_SRC / name, output / name)

    # Flip the page into static mode; app.js reads this to decide whether to
    # call the API or fetch prebaked payloads.
    index = (STATIC_SRC / "index.html").read_text(encoding="utf-8")
    if 'name="pva-mode" content="live"' not in index:
        raise RuntimeError("index.html is missing the pva-mode meta tag")
    index = index.replace('name="pva-mode" content="live"', 'name="pva-mode" content="static"')
    (output / "index.html").write_text(index, encoding="utf-8")

    (output / "config.json").write_text(
        json.dumps(_config(values, points), separators=(",", ":")), encoding="utf-8"
    )
    (output / ".htaccess").write_text(_HTACCESS, encoding="utf-8")

    runs_dir = output / "runs"
    if runs_dir.exists():
        shutil.rmtree(runs_dir)
    for scenario in SCENARIOS:
        (runs_dir / scenario.id).mkdir(parents=True, exist_ok=True)

    total = len(points)
    done = 0
    total_bytes = 0
    with ProcessPoolExecutor(max_workers=workers) as pool:
        futures = {
            pool.submit(
                _solve_point,
                {
                    "scenario_id": p.scenario_id,
                    "knobs": p.knobs,
                    "seed": p.seed,
                    "solver": STATIC_SOLVER,
                    "generations": STATIC_GENERATIONS,
                },
            ): p
            for p in points
        }
        for future in as_completed(futures):
            point = futures[future]
            payload = future.result()
            # The grid position is what the browser looks the file up by; keep it
            # in the payload so a downloaded run is self-describing.
            payload["gridKey"] = point.key
            text = json.dumps(payload, separators=(",", ":"))
            (output / point.rel_path).write_text(text, encoding="utf-8")
            total_bytes += len(text.encode("utf-8"))
            done += 1
            if progress is not None:
                progress(done, total)

    return {
        "runs": total,
        "bytes": total_bytes,
        "output": str(output),
        "grid": grid_name,
    }
